### ISSUE TITLE
Create Specification for the project 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#1]
What we need is

1. Specification for the CLI resigstry (Sample JSON including versions, binary locations etc.)
2. List of the required features and good haves

**Comment by ankithans** [comment]
@wtrocki sample specification for the CLI registry
```json
{
    "name": "",
    "description": "",
    "version": "",
    "environment": "",
    "registry": "",
    "homepage": "",
    "bin": {},
    "private": false,
    "dependencies": {

    },
    "maintainers": {

    },
    "license": ""
}
```

**Comment by ankithans** [comment]
Feats:
	- Use a CLI plugin as an extension in some CLI
	- Link multiple CLI's together
	- Registry Manager containing the list and metadata of CLI's
	- Github repo/pages based remote index servers for plugins which will contain docs, metadata of the plugin
	- Framework that will be able to read these remote index servers

**Comment by wtrocki** [comment]
Pretty much, but also logic for listing and downloading extensions. Logic for executing extensions in host CLI

**Comment by ankithans** [comment]
okay, I will start with a readme.

**Comment by wtrocki** [comment]
@ankithans I have pushed to main branch example registry. If we add more CLIs - Kubectl, and OC (OpenShift) then we can have reliable sample app that we can base on.

**Comment by ankithans** [comment]
> https://mirror.openshift.com/pub/openshift-v4/clients/

Okay, so we need this type of registry manager. Is it taking releases from GitHub?

**Comment by wtrocki** [comment]
I cannot assign you both but we really need to work on this for proposal this week to send i. @namit-chandwani @ankithans

**Comment by ankithans** [comment]
@wtrocki Now ATY what's left here?

**Comment by namit-chandwani** [comment]
> @wtrocki Now ATY what's left here?

+1
And how should we divide the remaining work among ourselves?

**Comment by ankithans** [comment]
@wtrocki 
shall we use this for Kafka?
```
 {
    "name": "kaf",
    "description": "Modern CLI for Apache Kafka, written in Go.",
    "version": "v0.1.39",
    "homepage": "https://github.com/birdayz/kaf",
    "binaries": {
      "darwin-amd64": "https://github.com/birdayz/kaf/releases/download/v0.1.39/kaf_0.1.39_Darwin_x86_64.tar.gz",
      "linux-amd64": "https://github.com/birdayz/kaf/releases/download/v0.1.39/kaf_0.1.39_Linux_x86_64.tar.gz",
      "windows": "https://github.com/birdayz/kaf/releases/download/v0.1.39/kaf_0.1.39_Windows_x86_64.tar.gz"
    },
    "dependencies": {},
    "tags": [],
    "license": "Apache License"
  }
```

**Comment by wtrocki** [comment]
That will be good. Yes
