### ISSUE TITLE
Refactor RuleConfig to accept slice of RuleInterface

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#110]
Instead of hardcoding every rule in RuleConfig, accept the array of RulesInterface that is implemented by every rule.
#### currently
```go
type RuleConfig struct {
	Verbose bool
	Length
	MustExist
}
```
#### What we want
```go
type Rules interface {
	Validate() []validator.ValidationError
}
type RuleConfig struct {
	Verbose bool
	Rules   []Rules
}
```

**Comment by dimakis** [comment]
+1 on the new proposed structure. This feels like it makes more sense. I think this should be done in its own PR ( my preference ) away from https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/433/ or at very least its own commit ( not my preference ).  It should make PR-433 easier to progress.

**Comment by ankithans** [comment]
Are you referring #105 ? Actually that PR was fixing a minor bug in the old structure, But as you see in this new structure, that change will not make any sense, hence no need to push that into main.
