### ISSUE TITLE
describe architecture in separate doc

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#117]
We need to describe architecture.in separate.doc:

- what is host cli
- what is plugin

Separate issue/PR please

_Originally posted by @wtrocki in https://github.com/aerogear/charmil/pull/108#discussion_r662543725_

**Comment by jackdelahunt** [comment]
This is definitely needed I am constantly getting confused on what we are calling things but also what we are trying to achieve with this project.

**Comment by namit-chandwani** [comment]
Resolved via PR: #132 ?

**Comment by wtrocki** [comment]
Project description != architecture. This one is more to talk about API, SDK etc.. Usage. Some diagram. Getting started guide could be duplicate of it.


<img width="1458" alt="Screenshot 2021-07-06 at 12 12 08" src="https://user-images.githubusercontent.com/981838/124590742-67cbe680-de53-11eb-8d3b-bd0f5c08428b.png">

**Comment by namit-chandwani** [comment]
Got it. Thanks!

**Comment by wtrocki** [comment]
Closing. Since there is no strong architecture patterns and we moved to starter architecture is not worth documenting deeply. What we have is good
