### ISSUE TITLE
Add docusaurus website with content from docs

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#129]
### Feature or problem description

We need clean documentation. No front page needed. No blog. Just documentation

https://docusaurus.io/

**Comment by wtrocki** [comment]
Reopened because we need to publish to gh-pahes.
If that is done feel free to close

**Comment by wtrocki** [comment]
https://aerogear.github.io/charmil/

**Comment by ankithans** [comment]
created new issue for that 😅, then we can close #140 or this

**Comment by wtrocki** [comment]
My bad.
