### ISSUE TITLE
Generate boilerplate starter with charmil commands

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#143]
As we will provide some starter examples to start developing, we may provide a CLI tool to generate a starter project/plugin instead of copying, just like cobra does.

**Comment by wtrocki** [comment]
Good idea. I'm working on pulling out the bits for initial project structure. There are common elements that can be templated like:

- cmd name
- repository name
etc.

https://github.com/Apicurio/apicurio-cli

Will provide more info about this once I got something working soon. Full blown generation might be too much but we can figure out something that will allow us to swap values

**Comment by ankithans** [comment]
Remove unnecessary feats from core and put them in starter. and Set up starter with Charmil core features
- Localization
- Autocompletion commands
