### ISSUE TITLE
Pull pkg from starter to charmil core

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#149]
#145 gives us a starter project, in which many elements should be present in charmil core.

**Comment by wtrocki** [comment]
It should be other way around (I think you meant that) - we should be removing things from starter and replace them with core SDK.

I already created issues for missing elements that are not on starter but can be in the core SDK and later integrated into starter

https://github.com/aerogear/charmil/issues/138
https://github.com/aerogear/charmil/issues/136
https://github.com/aerogear/charmil/issues/135
and couple more

**Comment by ankithans** [comment]
> we should be removing things from starter and replace them with core SDK.

yep, we can do them one by one, this can be our current priority now
