### ISSUE TITLE
Create go templates for starter CLI

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#164]
This will include 
- shell commands - cmd/CLI_NAME, pkg/cmd/root, etc
- License 
- Contributing.md
- .gitignore
- .golangci.yaml
- .goreleaser.yaml
- Makefile
- Readme.md

.github, .githooks etc can be specific to repository, hence should not be our business.

**Comment by namit-chandwani** [comment]
Just confirming. This is blocked till we completely refine starter, right?

**Comment by ankithans** [comment]
yes somewhat, let me do that in #155 with what we have. so we can proceed.
And templates can be updated, code for generating templates will be same

**Comment by wtrocki** [comment]
I will recomend to not do it. If somehow we can avoid our code as templates then we can have starter useful without CLI/asembly.

Issue is correct we need that just not sure if go templates are right way to do it

**Comment by ankithans** [comment]
> if go templates are right way to do it.

let me explore this today!

**Comment by namit-chandwani** [comment]
> This will include
> 
> * shell commands - cmd/CLI_NAME, pkg/cmd/root, etc
> * License
> * Contributing.md
> * .gitignore
> * .golangci.yaml
> * .goreleaser.yaml
> * Makefile
> * Readme.md
> 
> .github, .githooks etc can be specific to repository, hence should not be our business.

@ankithans So what do you think, should we include a `go.mod` file in this list too?
This way we will be able to force the starter to use our desired released version of core

**Comment by ankithans** [comment]
idts, so steps will be -
- go mod init
- go install charmil
- charmil init ...
- charmil add ...

**Comment by namit-chandwani** [comment]
Okay, I think that's what followed while using the Cobra starter too.

Cool, in that case we will need to make sure we update our templates every time we make any changes in `core`

**Comment by wtrocki** [comment]
> This way we will be able to force the starter to use our desired release of core

releases on starter will ensure this happening.

What charmil init and add do?

**Comment by wtrocki** [comment]
Lets try to minimize number of template files and maximize what we have in shell

**Comment by ankithans** [comment]
> What charmil init and add do?

https://github.com/aerogear/charmil/blob/main/docs/src/charmil_cli.md
> maximize what we have in shell

I think all the starter files will be templates 🤔. if we want to achieve above

**Comment by ankithans** [comment]
similar to this: https://github.com/spf13/cobra/blob/master/cobra/tpl/main.go

**Comment by wtrocki** [comment]
Like init command. If we can do it fast lets do it.
Really like create/add command although as well.
