### ISSUE TITLE
Reserach how to reuse krew implementation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#17]
Krew has a lot  of really good code that handle our cases. We need to research possible options to reuse some of the code/or inspire on krew without breaching license model or do any shady work.

**Comment by ankithans** [comment]
These seems to be the ways to reuse the krew implementation:
1. use krew as package sigs.k8s.io/krew
   - code we require to import is in internal directory, but here https://golang.org/doc/go1.4#internalpackages
   - it is written here `Sometimes one wishes to have components that are not exported, for instance to avoid acquiring clients of interfaces to code that is part of a public repository but not intended for use outside the program to which it belongs.`
2. copy required code into our repo
   - then may be create ACKNOWLEDGMENTS.md
   - or acknowledge on the top of every file
3. write code ourselves and take some help from krew in implementation

**Comment by wtrocki** [comment]
learned a lot from krew we can now avoid cloning their code and start with embedded approach
