### ISSUE TITLE
Add Interactive prompt mode to Charmil CRUD generator

### ISSUE THREAD

**Issue by namit-chandwani** [aerogear/charmil#177]
Low priority for now

### Additional context

https://github.com/aerogear/charmil/pull/171#discussion_r675034017

**Comment by ankithans** [comment]
@namit-chandwani i think it is not required. we can close this wdyt?

**Comment by namit-chandwani** [comment]
> @namit-chandwani i think it is not required. we can close this wdyt?

Any particular reason for the same?

I believe this will be a useful addition that can be implemented at a later stage :)

Like we can add an `interactive` flag to the charmil crud command and whenever the `interactive` flag is set, the generated CRUD commands will have the interactive mode enabled.

#### Example:
```bash
charmil crud --singular=kafka --plural=kafkas --interactive
```

WDYT?

**Comment by wtrocki** [comment]
Not needed.
