### ISSUE TITLE
Cleanup Core package

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#183]
### Feature or problem description

I have reviewed core package and it looks like what we have there is mostly non functional, undocumented or outdated.
Removing entire core at this point will result in no los in the value.

What we should do:

- Review every folder we have there
- Remove factory (as we agreed that factory is starter artifact not core artifact)
- Fix config - config is key for us to have proper modular architecture but provided solution doesn't seem to work.

**Comment by wtrocki** [comment]
CC @aerogear/charmil

**Comment by wtrocki** [comment]
I will create separate issue for config

**Comment by ankithans** [comment]
yeah, we don't have much in core

logging - functioning
color - functioning - used with logger  `f.Logger.Infof(color.Success("lorem ipsum"))`
localize - functioning as wrapper

iostreams - kinda non-functional - in, out streams are used
config - will be fixed

**Comment by wtrocki** [comment]
we can... Keep core untouched but non functional. Keep investing in starter (Which we do) and gradually improve state of the core with right packages.
