### ISSUE TITLE
Language file is dropped in random directory

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#190]
## Description

CRUD creates language file in random directory. (IMHO it should be part of the same folder - I can move things later)
Language file is not using name of the object we create nor name is used in the strings making entire generation unusable and pointless. 
Source code is referencing generic names - it is not possible to generate entire content twice.

**Comment by namit-chandwani** [comment]
> Language file is not using name of the object we create nor name is used in the strings making entire generation unusable and pointless.

I've made this change. Creating a PR for it shortly.

> CRUD creates language file in random directory. (IMHO it should be part of the same folder - I can move things later)

Actually, the way it works right now is that our code searches the entire CLI project for a `locales` directory and then generates the language file over there (ie. in `locales/en`). This eliminates the need for the user to relocate the file elsewhere. So won't it be better if we keep it this way?

Please correct me if I'm wrong :)

**Comment by wtrocki** [comment]
I would add flag for language files directory. If not specified it uses current folder. No magic search.

**Comment by namit-chandwani** [comment]
> I would add flag for language files directory. If not specified it uses current folder. No magic search.

Sounds good, will follow this
