### ISSUE TITLE
Feature to disable a validation rule

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#197]
User should be able to disable a rule, by passing a boolean "enable". Default set to true.

### Current
```go
type RuleOptions struct {
	Verbose      bool
	SkipCommands map[string]bool
}
```
### Proposed
```go
type RuleOptions struct {
	Disable       bool
	Verbose      bool
	SkipCommands map[string]bool
}

```

**Comment by ankithans** [comment]
I found two approaches to do this - 
- Stop rule from executing from RuleExecutor(means donot add the particular rule into rules array to execute)
- add rules to executor; execute the rule and inside each rule check if it is disabled - return empty errors.

I think first one is good? Need suggestions @aerogear/charmil

**Comment by jackdelahunt** [comment]
So what your saying in option 1 is to check before we add all of the rules [here](https://github.com/aerogear/charmil/blob/main/validator/rules/config.go#L84-L91)?  If this is where you are thinking about I would maybe suggest option 2 as option 1 feels like it is hidden away and is not an obvious place where we do that check. 

Option 2 which should just need an edit to this for loop [here](https://github.com/aerogear/charmil/blob/main/validator/rules/executor.go#L104-L109) I think so adding the check here would just make more sense.... for me atleast.

**Comment by wtrocki** [comment]
option 1

**Comment by ankithans** [comment]
> Option 2 which should just need an edit to this for loop here I think so adding the check here would just make more sense.... for me atleast.

here it cannot be done, as rule interface only has validate method, no access to RuleOptions. Let's go with option 1
