### ISSUE TITLE
Auto-generated links to source from Charmil docs are broken 

### ISSUE THREAD

**Issue by jackdelahunt** [aerogear/charmil#206]
## Description
On each page of the charmil documentation, there is an auto-generated link labeled `Edit this page` this link is broken.

### Steps to reproduce

Add the steps required to reproduce this error.

1. Go to [this page](https://aerogear.github.io/charmil/docs/)
2. Scroll down to the bottom of the page
3. Click `Edit this page`
4. Page is not found

### Expected vs actual behavior
When following the above steps the link sends you to:
`https://github.com/aerogear/charmil/tree/main/docs/docs/src/intro.md`.

This link should actually send you to:
 `https://github.com/aerogear/charmil/blob/main/docs/src/intro.md`. 

You can see that the broken link has an extra `/docs` in it.

**Comment by wtrocki** [comment]
Done. No edit is possible :P
