### ISSUE TITLE
Examples builder that provides base command instead of specifying command as string etc.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#218]
### Feature or problem description

Provide examples string builder that provides ability to generate full example string of the command and append to existing examples.
This will prevent typos and ensure standard way to build command examples - description + command + some extra flags etc.

## Example

```
## List all artifacts for the default artifacts group
rhoas service-registry artifacts list
```

can be done using builder
```
flagutil.NewCmdExample(cmd, "List all artifacts for the default artifacts group", "list --page=4")
flagutil.NewCmdExample(cmd, "List all artifacts", "list")
```

**Comment by wtrocki** [comment]
This can be also used as form of acceptance testing of commands etc.

**Comment by ankithans** [comment]
great idea!!
