### ISSUE TITLE
Ability to save command log/history

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#222]
We need ability to get history from user file for debugging and checking what caused issues.

**Comment by ankithans** [comment]
so whatever command user executes, store the logs(input/output) in a file. And whenever needed show it?
we can have some format datetime wise.

**Comment by wtrocki** [comment]
Like bash history but specific to your CLI (Or even some subcommand to your CLI (can be stored independently from config file)

**Comment by ankithans** [comment]
we may provide "history" command from core ```CLI_NAME history``` which can be imported in a CLI, which will return all the commands executed before. Can add argument for number of items in history to be shown.
`history 5`
`history delete` and many other options....

I think, we should store the output of the executed command as well.

Is this really a good first issue 😅

**Comment by wtrocki** [comment]
That was never intended to be user facing - as user have bash history for that. We have implemented analytics in rhoas but that requires asking user for permission. I would recommend to close this
