### ISSUE TITLE
Migrate rhoas CLI to use Charmil

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#225]
In https://github.com/aerogear/charmil-host-example, it needs to use charmil overall.
- localizer
- config - @namit-chandwani working rn on improving
- logger, iostreams, color
- autocompletion commands - #212 
- example_builder
- validator

**Comment by ankithans** [comment]
copying all the code and then migrating was not a good idea, it will take ages to fix those errors. Will be writting initial stuff on my own and then picking rhoas module by module.

**Comment by wtrocki** [comment]
Just seen it. What code to where? Maybe you want sync on approach?

**Comment by wtrocki** [comment]
What we should do

1) Push rhoas apicurio-cli branch to host with all commits etc.
2) Push the same codebase to plugin

3) Remove service-registry commands from host

4) Remove everything else than service registry commands from plugin

5) Sprinkle with charmil

6 Integrate and call it done :)

**Comment by wtrocki** [comment]
Hope that clarifies things
