### ISSUE TITLE
Refactor CLIs in example repos to use Charmil Core packages

### ISSUE THREAD

**Issue by namit-chandwani** [aerogear/charmil#234]
Refactor CLIs in repos: https://github.com/aerogear/charmil-host-example and https://github.com/aerogear/charmil-plugin-example, to use the Charmil Core packages.

**Comment by wtrocki** [comment]
What packages specifically?

**Comment by namit-chandwani** [comment]
> What packages specifically?
> Would you do all? Better to focus on config

Already did all packages (except config) through this PR: https://github.com/aerogear/charmil-host-example/pull/2
Now creating a separate PR for config package

**Comment by wtrocki** [comment]
Awesome!

**Comment by namit-chandwani** [comment]
This has been resolved already. Closing it now
