### ISSUE TITLE
`charmil init` generates broken git repo 

### ISSUE THREAD

**Issue by kadel** [aerogear/charmil#246]
## Description

Git repository created by `charmil init` has broken index.

### Steps to reproduce
- `charmil init`
- `git status`

### Expected vs actual behaviour

```
▶ charmil init
GitHub Organization or Username: test
GitHub Repo Name: test
CLI Name: test
Enumerating objects: 161, done.
Counting objects: 100% (161/161), done.
Compressing objects: 100% (97/97), done.
Total 161 (delta 49), reused 141 (delta 34), pack-reused 0
updating starter code with names
Your test CLI has been initialized in this directory.

▶ git status
fatal: unknown index entry format 0x1efa0000
```

**Comment by wtrocki** [comment]
Thank you for reporting issue. I think we should not generate .git repository. 

@ankithans this is probably due to using our template repo. I guess we can simply remove .git folder.

**Comment by ankithans** [comment]
yes, after cloning - we can remove .git folder. Will fix it.
