### ISSUE TITLE
Add methods for unified logging in commands 

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#51]
## Feature Description
Following methods can be added to ensure the logging and printing messages in unified way
Debug, Info, Warn, Error, Fatal, Panic, Trace, etc. using `fmt.Fprint()`, `fmt.Fprintf()`, `fmt.Fprintln()` functions

**Comment by ankithans** [comment]
we can provide colors for different types of logs, if that is useful @aerogear/charmil-core

**Comment by wtrocki** [comment]
That is distraction. Lets work on the core business.
