### ISSUE TITLE
Validator to ensure standard for commands

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#58]
So we removed the wrapper approach as a feasible way to drive our architecture, but despite not having it 
we still want to control some of the aspects of the commands. 

My take is that for this purpose we could have a linter/validator solution where we can specify different rules that will be interacting thru cobra commands and see if they are valid etc. We will provide default recommendations/ruleset but there should be also the possibility to provide a validator in the near future. 

This is the top-level issue we can create task issues once we discuss more how this would look like.

@ankithans some bits of your wrapper implementation might be very useful for that.

**Comment by wtrocki** [comment]
We need resarch first:

1) If something like this is not actually available right now 
2) if we want to write validator ourselves or use existing linting solution like: https://github.com/golangci/golangci-lint - not sure if that would even allow us to do what we want.

3) Discuss examples of rules we want to apply:

Example: Each command should have long and short description and example.

**Comment by wtrocki** [comment]
@ankithans Check comment above. I would love to get your replies to it :)

> We need research first

**Comment by ankithans** [comment]
> Discuss examples of rules we want to apply

as you already mentioned some of the rules, copying them here
- Command has examples 
- Short and Long description
- Each argument has a description
- Command has long and short description defined
- Command uses single positional argument (no multiple positional arguments) etc.

more
- Command has a Run function
- Defined number of arguments in command

For now couldn't think more useful

We can use this for docs/help (examples and Long)
https://github.com/MakeNowJust/heredoc

---
> if we want to write a validator ourselves or use an existing linting solution like golangci-lint

To use golangci-lint, don't we have to write validators ourselves using AST for cobra specific structure and then integrating that with golangci-lint?

---
one more ques:
if there is a possibility that we could extend the functions from cobra library not wrapping?

**Comment by wtrocki** [comment]
> one more ques:
if there is a possibility that we could extend the functions from cobra library not wrapping

What you mean by this. More detailed question

**Comment by ankithans** [comment]
In dart there is a feature to extend the library - modify, overriding existing methods

**Comment by wtrocki** [comment]
Sill no clue.. 
Done quick research and we can do:

1) Ast processor (go has core lib that enables and most of linters use it). It will work at compile time etc.

Benefits: It will be easy to make this popular, blog post it etc.

Drawbacks: Overkill for our needs, harder to add new rules 

2) In house cobra structure analiser with rules.
It can be cli on its own that needs to be compiled and will process rules and validate stuff.
https://github.com/redhat-developer/app-services-cli/blob/main/cmd/modular-docs/main.go

Benefits: Simple

Drawback: Kinda convoluted user experience (but we can actually improve it if this wil be some testing library instead of cli etc.

@aerogear/charmil-core Lets discuss and pick something here

**Comment by ankithans** [comment]
first one is clear enough.
not sure how 2nd one will work. Will it be based upon cobra library or AST processor?
