### ISSUE TITLE
[Wrapper] Rapid Creation of CRUD command line tools.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/charmil#67]
In some situations developers can avoid a lots of boilerplate if we enable them to have 

Imagine that you have CLI like RHOAS CLI - where there will be multiple services performing typical crud operations:

```
[wtrocki@graphapi app-services-cli (srs-management-cli ✗)]$ rhoas kafka
Create, view, use, and manage your Apache Kafka instances

Usage:
  rhoas kafka [command]

Available Commands:
  create        Create an Apache Kafka instance
  delete        Delete an Apache Kafka instance
  describe      View configuration details of an Apache Kafka instance
  list          List all Apache Kafka instances
  use           Set the current Apache Kafka instance
  
```

Adding new service usually means duplication of the commands, error handling etc.
We should research if we can provide some clever plugin (still using charmil core factory)

**Comment by wtrocki** [comment]
See kubernetes CLI for inspiration

**Comment by wtrocki** [comment]
My take is we can have some separate issues that are more detailed or keep this issue opened until we have it fully done and tested. Fell free to close if you want to work with more granular issues

**Comment by ankithans** [comment]
great! 
@namit-chandwani let's create follow up issues as well, they really helps in progressing.

**Comment by namit-chandwani** [comment]
Yes, so I'm listing down some of the possible issues:
- Generate locale file for CRUD commands
- Whenever the `crud` command is run, verify whether a CLI has already been initialized using the `charmil init` command.
- Set up config from core
- [Optional] Add Interactive prompt mode (Ref: https://github.com/aerogear/charmil/pull/171#discussion_r675034017)

Please feel free to suggest more :)
I'll create all issues once the list is finalized.

CC @wtrocki @ankithans

**Comment by ankithans** [comment]
> Whenever the crud command is run, verify whether a CLI has already been initialized using the charmil init command.

i think it should check if cli is there or not, not necessarily with charmil init, may be no need to check.

**Comment by namit-chandwani** [comment]
> i think it should check if cli is there or not, not necessarily with charmil init, may be no need to check at all.

I believe if we're using some core features like config, etc., allowing developers to use only the CLI generated using `charmil init` would be better.

But still I'm not 100% sure about this, will get to know better only once we proceed to work on these.

What is your take on this @wtrocki?

**Comment by wtrocki** [comment]
We would not be able to do most of those without adding arguments to those commands

**Comment by wtrocki** [comment]
> Whenever the crud command is run, verify whether a CLI has already been initialized using the charmil init command.

Not sure I get how init matters here.
Init is just convininence method. 
We have runnable starter app already right?

> I believe if we plan to use some core features like config later, allowing developers to use only the CLI generated using charmil init would be better.

But charmil init just does setup starter and replaces cli name. We have starter in repo with all core already?
I need more context for this - possibly @ankithans can speak for the state we have.

We could have quick chat about it next week.

**Comment by namit-chandwani** [comment]
> We could have quick chat about it next week.

Sure!
I'll just summarize the entire discussion for you till then. 

Ankit: Prefers allowing developers to use their own CLI to run `charmil crud`

Me: Prefer restricting developers to use the CLI that we provide (starter). And this can be achieved by enforcing them to run `charmil init` before `charmil crud`

**Comment by wtrocki** [comment]
Lets avoid building conflict in technical conversation.
What we have here is classical higly integrated dev vs less refined one.

I get we have some preferences but want to know why we want to restrict that. Technical reasons will be enough to get us there

**Comment by ankithans** [comment]
> We have starter in repo with all core already?

Actually I moved starter to a new repo, under my username, can be moved to aerogear. https://github.com/ankithans/charmil-starter-template. What we have in core is integrated.
Not maintaining the starter folder that we have in repo.

Will make a Makefile in the template repo, to do the similar things done by `charmil init` after cloning the repo manually.

**Comment by wtrocki** [comment]
> Actually I moved starter to a new repo..

Lets assume that what we have in repo is our current starter and discuss getting separate repo

**Comment by namit-chandwani** [comment]
> I get we have some preferences but want to know why we want to restrict users to use charmil init and what this init does that charmil repo doesnt. Technical reasons will be enough to get us there.

Actually, my primary take is to allow developers to only use our starter CLI with `charmil crud`.

And one of the ways to achieve this was by restricting them to run `charmil init` before `charmil crud`, which is why I mentioned it earlier (as through this approach we are ensuring that they're using the charmil starter CLI).

I'm open to any alternative ways to verify this. 

The only thing I was concerned about was allowing developers to use their own CLI (not starter), as I feel this might restrict us in the future when we add more features to the charmil crud command.

As I mentioned before, I may be wrong here so please feel free to correct :)

**Comment by wtrocki** [comment]
> Actually, my primary take is to allow developers to only use our starter CLI with charmil crud.

Ok

> And one of the ways to achieve this is by restricting them to run charmil init before charmil crud

What this will achieve? 
Init doesnt do anything that will affect crud command.
Nor changes much in template.

> The only thing I was concerned about was allowing developers to use their own CLI (not starter), as I feel this might restrict us in the future when we add more features to the charmil crud command.

With all respect I think we overthinking things a bit and introduce confusion.
Lets not complicate things when not needed.

**Comment by namit-chandwani** [comment]
> Users will use starter template init or clone..Whatever and then use crud, but no need.to restrict it

Got it, thanks :)
