### ISSUE TITLE
Configuration storage and abstraction for plugin

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#69]
For a clean default configuration, yaml files can be used. [viper](https://github.com/spf13/viper) might be useful here which is used by cobra as well!

**Comment by wtrocki** [comment]
Ther the is no such thing as default configuration.
Basically plugin commandline can exist on it's own and have their own config. 
If we include that in host CLI we ending up with 2 configs - not good. 

We need to have a way to compose config and share some common parts. 
This is blocked by figuring out authentication to the CLI etc.
