### ISSUE TITLE
Investigate ways to store Secrets in config (eg. OAuth token)

### ISSUE THREAD

**Issue by namit-chandwani** [aerogear/charmil#71]
Secrets are sensitive data that should be stored safely with strict access controls. API keys, encryption keys, OAuth tokens, certificates, PEM files, passwords, and passphrases are some examples of secrets. These might easily get exposed and compromised if not stored in an encrypted and secure way.

Through this issue, we aim to investigate ways in which we can store Secrets securely.

**Comment by wtrocki** [comment]
We need find lib that does this.
Issue has Low priority for now
