### ISSUE TITLE
Dependency of plugins on other plugins

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#78]
Plugins can be dependent on some plugin and they can reuse the code

**Comment by wtrocki** [comment]
This is very unrefined requirement to even start with. 

Idea was based on previous architecture that I had in mind. To transform things to new architecture.

Imagine that factory provides number of abstractions and technically you can swap them if need. 
I do not think we ready to even discuss this issue. Ok to close

**Comment by ankithans** [comment]
Okay let's close this for now!
