### ISSUE TITLE
Regex validation for command name

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#84]
useMatches that accept valid regexp that checks command name
Provide rule that validates if cmd doesn;t have _ or - etc. 

related to #58

**Comment by ankithans** [comment]
what seems most obvious from below two? We take input of regexp from the user(set the default exp until the user overrides)
- Use should match the given regexp
- Use shouldn't match this given regexp

And this rule should only check `Use` of cobra.Command, checking other attributes with regex will not be useful

**Comment by wtrocki** [comment]
Use should match the given regexp - this
