### ISSUE TITLE
Enhance logger for verbose logging

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#88]
stdnerr should be used for debug to get meaningful info (likrnjson) into std out.

**Comment by wtrocki** [comment]
I have context for this issue but without it I will be hard to get what you mean.

Best to put example code. How it is now and how it should be

**Comment by ankithans** [comment]
Now we pass a `Sprintf` statement in ValidationError, but this should not be used for debugging purposes. 
```go
return validator.ValidationError{
	Name: fmt.Sprintf("length should be at least %d", limit.Min), 
	Err: ErrLengthMin, 
	Rule: LengthRule, 
	Cmd: cmd,
}
```
To solve this issue we can add some more functionalities in logger and use that entirely!

**Comment by wtrocki** [comment]
Actually this is about using std.err instead of std.in in fmt.Print and other functions.
