### ISSUE TITLE
Validation: RuleExecutor for the rules

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#89]
Rules are doing a lot of responsibility. Ideally rules should do only rule validation. We should put all common elements into some ruleExecutor etc.

**Comment by jackdelahunt** [comment]
Hey @ankithans I just wanted to ask for more clarity on this, can you describe/show what we are you doing now that you want to solve and just a small description of how you think this could be done. I am just not sure what you are talking about with this issue.

**Comment by jackdelahunt** [comment]
After looking more in depth into #82 I think I might understand what you mean here. Is what you are proposing is to move the execution of the rule into `RuleExecutor` and keep the rule with the fields the user creates and a callback the `RuleExecutor` calls.
```
myExistRule := &rules.MustPresent{
    Fields: []string{"Use", "Short", "Long", "Example", "SilenceUsage", "PreRun", "Hi"},
}

validationErrors := RuleExecutor.executeRule(myExistRule, cmd)
```

**Comment by ankithans** [comment]
yes, exactly.. we can reuse the part of execution of rules. As execution is same for all. I am not sure how to approach. But we can do some hands on and figure it out.

**Comment by wtrocki** [comment]
#82 - has some proposed API. 
https://github.com/aerogear/charmil/discussions/61 - does describe how we should be doing work in next PR's.

> I think I might understand what you mean here.
> validationErrors := RuleExecutor.executeRule(myExistRule, cmd)

I think it will be better to do something like:
```
validationErrors := RuleExecutor.executeRules(cmd)
```

**Comment by ankithans** [comment]
So now in #82 we have execution for each rule separately, but in this issue, we want to execute all the rules at once..

**Comment by wtrocki** [comment]
@ankithans not all. Take look how usually linters work - eslint, golangci lint. This is required work to start writing linter :)

I will TL:DR to you:

- Linters initialize all rules by default but they are driven by config - can be enabled, reconfigured or adjusted severity level - error, warn, ignore etc.
- Linter executes rules by checking config and executing rules based on the configs.
- It is required for every linter to have set of **default configurations** that you can override if needed

Let's work on this issue now as I do not see us providing our desired user facing API without it.

**Comment by jackdelahunt** [comment]
So from what I understand we will have one config per rule you want to use. You then configure how the rule works like adding string to the fields for the `mustExists` rule. Then running the rule executor below it runs all rules assigned to that commands as defined in the config files.
```
validationErrors := RuleExecutor.executeRules(cmd)
```

**Comment by wtrocki** [comment]
> So from what I understand we will have one config per command.

Do you mean cobra command? Cobra commands are processed by the same rules and config. 
We could add way to disable some command processing - issue here https://github.com/aerogear/charmil/issues/86

> You then configure which rules the commands uses 

In flow commands are passive. Is is rules that process commands.
Look at this 1 min diagram:
```
RuleEngine    RulesGlobalConfig           
     |                   /
    V                 V              <uses>
    Rules (1...*)         < ---------------> [Rule Executor]    ---->   [Rule execution results/errors] 
       | <operates>                                            | <traverse>
      V                                       <uses>            V
 [Cobra Command]     < ---------------  [Cobra CMD root] 

```

**Comment by jackdelahunt** [comment]
Okay I think I understand this more now. I am just curious to see how the config for the rules will look like now.

**Comment by wtrocki** [comment]
@jackdelahunt Those things are standard and we should really follow what other linters do.
Example: https://eslint.org/docs/user-guide/configuring/

The difference for us is that we might not need yaml/json for now - golang struct will do as well

**Comment by ankithans** [comment]
I have tried things 

Created `RuleConfig` struct for configuration of rules
```go
type RuleConfig struct {
	Verbose       bool
	LengthRule    Length
	MustExistRule MustExist
}
```
## User API

```go
// we can override the default stuff, but here I am using default 
// here by default all rules are disabled or we can do vice versa
var vali rules.RuleConfig = rules.RuleConfig{
	Verbose: true,
	Length: rules.Length{
		Enable: true,
	},
	MustExist: rules.MustExist{
		Enable: true,
	},
}
validationErrors := vali.ExecuteRules(cmd)
```
or
```go
var vali rules.RuleConfig
validationErrors := vali.ExecuteRules(cmd)
```

**Comment by jackdelahunt** [comment]
I rather the use of a go struct for this, yaml or json for me seems unnecessary currently.  

Also I think a default of enabled here is probably better, when adding a rule to a rule config you expect it to be enabled unless you specify otherwise. 

Also the hard coding of the rules into the rule config struct seems like we could run into issues with the implementation of how we execute the rules. I suggest just being able to add any rule you want into some `rules` field in the rule config as then we just need to iterate over the `rules` and execute each one.

**Comment by ankithans** [comment]
> Also the hard coding of the rules into the rule config struct seems like we could run into issues with the implementation of how we execute the rules*. I suggest just being able to add any rule you want into some rules field in the rule config as then we just need to iterate over the rules and execute each one.

So here do you mean accept []string of rules?
> *Unless if I am missing a scenario in which we would want to explicitly define each rule in the rule config

yep user should be able to override the properties of rule, as we provide some default settings. But user might want to change them.

**Comment by jackdelahunt** [comment]
> So here do you mean accept []string of rules?

Here I meant accepting an array of structs that comply to the rule interface.

> yep user should be able to override the properties of rule, as we provide some default settings. But user might want to change them.

Hmm okay I thought that we would just let the user add the rules we provide to their own rule config as they want and make overriding changes at that point.

**Comment by wtrocki** [comment]
I think we have two core issues here:

1) Our rule structures that are implementations are used also as configs - If we separate them then all rules can be initialized and later we can do processing based on config

2) 
> Also I think a default of enabled = true here is probably better

Exactly. Minimize input from user - meaning that we should have default config and merge it with user config. 
Default config should have all rules enabled with some default (less restrictive values that we should extabilish).

Typically if we nail defaults most of the users will be happy with them.

This is really good conversation! Thank you @jackdelahunt and @ankithans for doing this exercise. Really we reaching breaking moment where we will get some nice vision how this will work.

**Comment by jackdelahunt** [comment]
Okay so just thinking about this more and I think this is what we could use. The API implementation I wrote is probably not what we want but just something to suggest.

User created config file in json or yaml
```
{
         customRules: [
		{
			name: "mustExist",
			enabled: false,
			verbose: true,
			fields: [
				"Use",
				"Short",
				"Long",
				"Example",
			],
		},
		{
			name: "length",
			enabled: true,
			verbose: false,
			minLength: 5,
			maxLength: 10
		}
	]
}
```
Then our api can provide a default config, load they own config or apply the custom one to the default overriding the rules based on the `name` field.
```
ruleConfig := validator.DefaultRuleConfig;
ruleConfig := validator.LoadCustomConfig(...);
ruleConfig := validator.DefaultRuleConfig.ApplyCustomConfig(...);
```

**Comment by wtrocki** [comment]
> User created config file in json or yaml 

That will work well when linter will be CLI. Not so well when linter is done as part of unit tests. We are still waiting for @ankithans for this secret info how this linter will be used. So far we have been mentioning unit test and CLI but nothing formal presented yet.

> Then our api can provide a default config, the load their own config or apply the custom one to the default overriding the rules based on the name field.

Yes. Pretty standard, however actual code will be more close to this: 
https://stackoverflow.com/questions/47395430/merge-fields-two-structs-of-same-type

**Comment by ankithans** [comment]
> Also I think a default of enabled = true here is probably better
> Minimize input from user - meaning that we should have default config and merge it with user config
> Then our api can provide a default config, the load their own config or apply the custom one to the default overriding the rules based on the name field.

nice, we can do this!

I have tried doing unit tests, validator works well as unit tests. I will provide the code for that in #82 
[noob question] how will we provide cobra command from a file to the CLI we make. Read the file?

**Comment by wtrocki** [comment]
> I have tried doing unit tests,

Best news! Lets create follow up issue for CLI.
For tests we can also provide more friendly method names
