### ISSUE TITLE
Use command validator as CLI

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#90]
Currently we are using validator as Unit test framework. While writing tests for a cobra command, `ExecuteRules` function can be executed which will return a slice of `ValidationErrors`.
But as most of the users will prefer a CLI tool for this, there will some significant changes to be made in validator API, which are yet to be explored!

All the `RuleConfig` can be loaded from a json/yaml file into the CLI.

(https://github.com/aerogear/charmil/issues/89#issuecomment-869746695) 
If we make CLI for validating commands then how will we provide cobra command from a file to the CLI. Read the file?

**Comment by jackdelahunt** [comment]
Can you layout the issue a bit more here. I think I know what you mean but I am not sure.

How I see the commands validator as a cli is you build with all the commands you want to add and the rules you setup with a config file. Then from that build we run `charmil validate` or something like that. This then runs each rule as defined by us or by the config file on each commanded added.

**Comment by wtrocki** [comment]
Thank you @jackdelahunt for keeping eye on issues and validation. This is hugely benefitial for students and brings diversity.

> How I see the commands validator as a cli is you build with all the commands you want to add and the rules you setup with a config file. Then from that build we run charmil validate or something like that. This then runs each rule as defined by us or by the config file on each command added.

This is 100% correct with what I was thinking.
We both know that this will require more work/steps comparing to unit tests approach.

**Comment by ankithans** [comment]
> Can you layout the issue a bit more here. I think I know what you mean but I am not sure.

updated, thanks for pointing out!

> How I see the commands validator as a cli is you build with all the commands you want to add and the rules you setup with a config file. Then from that build we run charmil validate or something like that. This then runs each rule as defined by us or by the config file on each command added.

okay, we can use binary of a CLI(which we want to validate), and pass that binary into `charmil validator CLI`. Then how we will access the attributes of cobra.Command to validate(like Use, Short etc). Binary will only allow use to use the CLI.
or I am taking `build` in wrong sense?

**Comment by wtrocki** [comment]
> okay, we can use binary of a CLI(which we want to validate), and pass that binary into charmil validator CLI

We will need to compile our code + cobra commands into executable, but maybe there is some golang trick to build tool that does something at compile time (probably not)

**Comment by jackdelahunt** [comment]
@wtrocki and @ankithans is it okay if I tackle this issue? If this was expected to be done by the students that I am okay to leave it to them.

**Comment by wtrocki** [comment]
@jackdelahunt I admire your passion. This is very good issue to take by anyone because:

- it is not on critical path
- is requires extensive research and non trivial approaches 
- When done it will probably invalidate our current unit test approach which is strange
- It will allow us to do rules as yaml/json

Note is that we adjusted our validator approach towards simplicity and implementation speed.
To do proper linter for golang we would need to use AST processor that would not have such challenge

**Comment by jackdelahunt** [comment]
Have we discussed how we want to introduce charmil commands anywhere this could be an interesting topic that could help clearing up what needs to be done with this issue.

**Comment by ankithans** [comment]
I think we have discussed about the commands previously #19 , but that is too outdated and will be useless for this issue in my opinion.

**Comment by jackdelahunt** [comment]
My main sticking point with this ticket is that we do not have any way to serperate host commands and custom commands. This is a 2 minute diagram of what I am thinking please tear it to pieces. 

```
charmil captures input  or  host captures input (not sure what we are doing here)
            |    		|
	    |			|
	    ---------------------
	    |		
	    |
	    v
process input(provider, comman, flags, fields)
	    |
	    |						charmil
	    L------------ charmil provider -----------> command
	    |						index
	    |							
	    |
	    |
	    |						host
	    |------------- host provider -------------> command
	    						index
```

**Comment by ankithans** [comment]
What is host here?
Is it from the examples directory? if yes then to clear this, host is nothing and don't contribute to the charmil core.
It's just an example to show how charmil can be used

**Comment by jackdelahunt** [comment]
Host is the project that is using charmil, so in our project host would add a new command called date to there index etc. etc.

**Comment by jackdelahunt** [comment]
Well I wasn't thinking the host as binaries but we capture the input and wither point it to the host commands or the charmil commands. This can be done in one binary the host builds to.

**Comment by ankithans** [comment]
okay, got your point, that will be epic. Sorry for taking too long to understand 😅. I had just a simple CLI in mind, separate from host.

**Comment by jackdelahunt** [comment]
I think before we do anything we should probably have some architecture diagram of what we actually want. So we can all be in sync because I agree that sometimes it is hard to figure what other people are talking about. Well I guess that could be the first commit the documentation!!

**Comment by jackdelahunt** [comment]
@ankithans so I made a WIP pr relating to this diagram I suggested, this is how I think adding charmil commands along side host defined ones can work but as always please scrutinise. cc @wtrocki

**Comment by jackdelahunt** [comment]
@ankithans Do we have any idea on how we want to handle stdin and how we parse that into what command we want to run. Or are we leaving this up to the host app to figure out.

**Comment by ankithans** [comment]
Actually cobra handles it automatically, when we declare `Use` in cobra.Command, it will detect the command name and run it(if the command has a Run/RunE func - then it runs that || otherwise it runs as help command showing Use, Short, Long etc)

**Comment by jackdelahunt** [comment]
Okay that makes sense but the stage leading up to this, getting input from the console and then letting cobra figure out which command to run based on use.

**Comment by ankithans** [comment]
> getting input from the console and then letting cobra figure out which command to run based on use.

cobra can do this for us...

**Comment by jackdelahunt** [comment]
> cobra can do this for us...

Okay

How I described we take the input and find out which provider it uses and run that command, cobra has no idea what a charmil command is vs a host command; and making the host have to add charmil commands to their root command would be bad no?

**Comment by ankithans** [comment]
Okay imo there are two options
1. consider it as 2 CLI's host & charmil. So charmil will provide validate command which can be used as `charmil validate ...`. Here host and charmil CLI don't interfere with each other. 

2. charmil CLI as plugin for the host(subcommand). this way we will be able to provide the `root command` of host for validation very easily. And command will be like `host charmil validate ....`

**Comment by jackdelahunt** [comment]
Okay option 2 is obviously easy to setup. But without anything other input we would require the host to add the charmil commands as a subcommand right?

**Comment by ankithans** [comment]
Yes, this will be required as charmil becomes a plugin here. 
```go
root.AddCommand(Charmil(root))
```
Here we can pass the root to validator very easily, if we have any alternative solution to this?

**Comment by wtrocki** [comment]
> root.AddCommand(Charmil(root))

This is widely impractical because you going to add command to the cli you do not want to have in production - this is only dev time thing

**Comment by ankithans** [comment]
Npm supports dev packages, can we have something like that in plugins here #72

**Comment by jackdelahunt** [comment]
Is the `--dev-preview-command` not in production aswell though but just cornered off. 
But maybe you are expecting use to disable this flag in prod.

**Comment by wtrocki** [comment]
Dev preview command is to not show commands that are still in QA. This has nothing to do with commands that are used to aid development (typically you do not want anything like that in your CLI)
